# Generated by Django 5.0.2 on 2024-02-29 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('audio_id', models.CharField(db_column='id', max_length=22, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('danceability', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('energy', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('key', models.PositiveSmallIntegerField()),
                ('loudness', models.FloatField(validators=[django.core.validators.MaxValueValidator(0)])),
                ('mode', models.BooleanField()),
                ('acousticness', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('instrumentalness', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('liveness', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('valence', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('tempo', models.FloatField()),
                ('duration_ms', models.CharField(max_length=10)),
                ('time_signature', models.PositiveSmallIntegerField()),
                ('num_bars', models.PositiveSmallIntegerField()),
                ('num_sections', models.PositiveSmallIntegerField()),
                ('num_segments', models.PositiveSmallIntegerField()),
                ('audio_class', models.BooleanField(db_column='class', verbose_name='class')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audio',
            },
        ),
    ]
