# Generated by Django 5.0.2 on 2024-02-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audiomodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='audio_class',
            field=models.PositiveSmallIntegerField(db_column='class', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='audiomodel',
            name='mode',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
